name: 'dbt_ons_bics'
version: '1.0.0'
config-version: 2

profile: 'postgres'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_ons_bics:
    staging:
      +materialized: view
    marts:
      +materialized: table
